# Managed by Dependabot. See https://docs.github.com/code-security/dependabot
version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Asia/Jerusalem"
    open-pull-requests-limit: 5
    labels: ["dependencies"]
    groups:
      terraform:
        applies-to: version-updates
        update-types: ["minor", "patch"]
